public with sharing class MaskSObjectConstants {

	/**
	 * MaskSObjectField__c
	 */

	//Action__c
	public static final String ACTION_ERASE = 'Erase';
	public static final String ACTION_REPLACE = 'Replace';
	public static final String ACTION_OBFUSCATE = 'Obfuscate';
	public static final String ACTION_RANDOMIZE = 'Randomize';

	//ActionType__c
	public static final String ACTION_TYPE_HARDCODED = 'Hardcoded';
	public static final String ACTION_TYPE_DICT_FIRST = 'Dictionary.firstname';
	public static final String ACTION_TYPE_DICT_LAST = 'Dictionary.lastname';
}
